[build.environment]
NODE_VERSION = "20.11.1"
SECRETS_SCAN_SMART_DETECTION_ENABLED = "false"

[build]
command = "rm -rf node_modules && npm cache clean --force && npm install -g npm@10.7.0 && pnpm install && npm run build"
